export const verifiedOn = '29 September 2026';
export const properties = [
 {id:164,title:'A panorama to call your own',location:'Kargicak, Alanya',type:'Penthouse',filters:['Apartments','Sea view','Luxury'],beds:2,baths:2,size:'147 m²',price:'€250,000',image:'property-164',alt:'The sea-view balcony of ALV property 164, a furnished Kargicak penthouse',caption:'PENTHOUSE · 180° VIEWS',kind:'Property photograph'},
 {id:165,title:'Space for a quieter kind of life',location:'Kızılcaşehir, Alanya',type:'Villa',filters:['Villas','Sea view','Luxury','Payment plan'],beds:3,baths:3,size:'200 m²',price:'€585,000',image:'property-165',alt:'Architectural visualisation of ALV property 165, a three-bedroom villa in Kızılcaşehir',caption:'VILLA · PRIVATE POOL',kind:'Architectural visualisation'},
 {id:2,title:'Life on the first coastline',location:'Kargicak, Alanya',type:'Apartment',filters:['Apartments','Sea view','Sea front'],beds:2,baths:2,size:'95 m²',price:'€250,000',image:'property-2',alt:'Shared infinity pool of ALV property 2’s Kargicak apartment development at sunset',caption:'APARTMENT · FIRST COASTLINE',kind:'Shared amenity photograph'},
 {id:154,title:'An island retreat in Batu Belig',location:'Batu Belig, Bali',type:'Apartment',filters:['Apartments','Bali','Sea view'],beds:null,baths:null,size:'From 82 m²',price:'From €180,000',image:'property-154',alt:'Project visualisation of the courtyard and shared pool at ALV property 154 in Batu Belig, Bali',caption:'APARTMENTS · BALI',kind:'Project visualisation'}
];
export const categories=[['Sea-front properties','sea-front-properties','Sea front'],['Sea-view properties','sea-view-properties','Sea view'],['Private villas','villas','Villas'],['Luxury apartments','luxury-apartments','Apartments'],['Investment opportunities','invest',null]];
export const steps=[['Discover','We start with your priorities, your intended use and your timeline. A focused brief makes a focused search possible.'],['Evaluate','Our team helps you weigh the location, property and pricing, with local knowledge and an established network of partners.'],['View','Explore a shortlist in person or ask for a live video viewing through ALV’s TeleVideoProperty service.'],['Negotiate','ALV represents your interests in price discussions and helps coordinate clear purchase agreements.'],['Complete & settle in','Receive guidance through the legal transfer and ask the team about support after your purchase.']];
export const services=[['Our full service','our-full-service'],['Before the purchase','before-purchase'],['After the purchase','after-purchase'],['Costs and fees','costs-and-fees'],['Title deed in Türkiye','title-deed'],['TeleVideoProperty','televideo-property'],['Citizenship procedures','turkish-citizenship']];
