import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { properties, categories, steps, services, verifiedOn } from './data.js';
gsap.registerPlugin(ScrollTrigger);
const $ = s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const official='https://www.alv-homes.com/';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(p,i)=>`<a class="property-card" href="${official}properties/id${p.id}" target="_blank" rel="noopener" data-index="${i}" aria-label="${escape(p.type+' in '+p.location+', '+p.price+'. View official listing '+p.id+' (opens in new tab)')}"><div class="property-image"><img src="/assets/${p.image}.webp" width="1000" height="667" alt="${escape(p.alt)}" loading="lazy"><span class="property-tag">${escape(p.type.toUpperCase())}</span><span class="property-id">ALV / ${p.id}</span><span class="image-kind">${p.kind}</span></div><div class="property-info"><div class="property-meta"><span>${escape(p.location.toUpperCase())}</span><span>${p.caption.split(' · ')[0]}</span></div><h3>${escape(p.title)}</h3><div class="property-facts">${p.beds?`<span>${p.beds} bedrooms</span><span>${p.baths} bathrooms</span>`:'<span>1–2 bedroom options</span>'}<span>${p.size}</span><strong>${p.price}</strong></div></div></a>`;
const stepsHTML=()=>steps.map((s,i)=>`<details ${i===0?'open':''}><summary><span>0${i+1}</span><h3>${s[0]}</h3></summary><p>${s[1]}</p></details>`).join('');
$('#property-rail').innerHTML=properties.map(card).join('');
$('#categories').innerHTML=categories.map((c,i)=>`<a href="${official+c[1]}" target="_blank" rel="noopener"><span>0${i+1}</span><h3>${c[0]}</h3><small>EXPLORE</small></a>`).join('');
$('#journey-steps').innerHTML=stepsHTML();
const top=(label,title,copy)=>`<section class="route-top"><p class="eyebrow">${label}</p><h1 tabindex="-1">${title}</h1><p>${copy}</p></section>`;
const templates={
properties:()=>top('THE ALV COLLECTION','Find your <em>perspective.</em>','A selection of homes in Türkiye and Bali. Find a place that fits the life you have in mind.')+`<section class="catalog"><div class="filter-bar" aria-label="Filter properties">${['All','Villas','Apartments','Sea front','Sea view','Bali','Luxury','Payment plan'].map((f,i)=>`<button data-filter="${f}" aria-pressed="${i===0}">${f}</button>`).join('')}</div><p id="catalog-count" class="catalog-count" aria-live="polite"></p><div class="catalog-grid" id="catalog-grid"></div><div class="catalog-note"><p>Published asking prices checked ${verifiedOn}.<br>Availability and final terms are confirmed by ALV.</p><a class="button" href="${official}buy-rent" target="_blank" rel="noopener">View the complete ALV collection</a></div></section>`,
markets:()=>top('OUR MARKETS','A world of <em>possibility.</em>','Different places call for different knowledge. Begin with the setting, then consider how it fits your plans.')+`<section class="editorial-page"><div class="editorial-split"><img src="/assets/turkey.webp" width="1000" height="667" alt="Alanya harbour and Red Tower in Türkiye"><div class="editorial-copy"><p class="eyebrow">01 — TÜRKİYE</p><h2>The coast.<br><em>And beyond.</em></h2><p>From Mediterranean neighbourhoods to major cities, Türkiye offers distinct property markets. ALV considers each location in relation to your lifestyle, practical needs and intended ownership period.</p><a class="under-link" href="${official}why-turkey" target="_blank" rel="noopener">Explore Türkiye</a><a class="under-link" href="${official}buyturkey" target="_blank" rel="noopener">Türkiye listings</a></div></div><div class="editorial-split"><div class="editorial-copy"><p class="eyebrow">02 — BALI &amp; SURROUNDING ISLANDS</p><h2>An island.<br><em>Your own rhythm.</em></h2><p>Bali, Nusa Penida, Lombok and the Gili Islands have different characteristics. ALV’s approach considers local rules, ownership arrangements and intended use before matching a destination to your goals.</p><a class="under-link" href="${official}why-bali" target="_blank" rel="noopener">Explore Bali</a><a class="under-link" href="${official}buybali" target="_blank" rel="noopener">Bali listings</a></div><img src="/assets/bali.webp" width="1000" height="661" alt="Kelingking Beach on Nusa Penida, in the Bali and surrounding islands market"></div><div class="editorial-copy"><p class="eyebrow">03 — THAILAND</p><h2>A personal conversation.</h2><p>Thailand is part of ALV’s international advisory focus. Contact the team to discuss your preferred area and currently available opportunities.</p><a class="button" href="#contact">Discuss Thailand</a></div></section>`,
services:()=>top('OUR SERVICES','Clarity at <em>every step.</em>','Personal guidance through the decisions, details and conversations that shape a property purchase.')+`<section class="journey section-pad"><div class="journey-intro"><p class="eyebrow">A STRUCTURED APPROACH</p><h2>Your goals.<br><em>Our full attention.</em></h2><p>ALV helps buyers with selection, evaluation, negotiations and coordination through transfer. Sellers can discuss positioning, pricing and reaching international buyers.</p><a class="under-link" href="#contact">Discuss your plans</a></div><div class="journey-steps">${stepsHTML()}</div></section><section class="editorial-page"><p class="eyebrow">EXPLORE THE DETAILS WITH ALV</p><h2>A little more <em>understanding.</em></h2><div class="service-links">${services.map(s=>`<a href="${official+s[1]}" target="_blank" rel="noopener">${s[0]}</a>`).join('')}</div></section>`,
about:()=>top('OUR STORY','A more personal<br><em>perspective.</em>','A boutique agency with an international outlook, based in Alanya.')+`<section class="editorial-page"><div class="editorial-split"><img src="/assets/turkey.webp" width="1000" height="667" alt="Alanya, home to ALV Homes"><div class="editorial-copy"><p class="eyebrow">ROMIOU SHAIKH · FOUNDER &amp; CEO</p><h2>Property decisions.<br><em>Life decisions.</em></h2><p>ALV works with buyers, sellers and investors whose reasons for purchasing go beyond an address. Its advice draws on first-hand investment experience, local relationships and a structured approach to evaluating opportunities.</p><p>The team combines property selection with negotiation support and coordination through the transaction. The starting point is your purpose: a holiday home, a permanent move or an international property portfolio.</p><a class="under-link" href="${official}our-story" target="_blank" rel="noopener">Read ALV’s story</a></div></div><div class="statement-quote">“Our work is selective. Our advice is independent. We focus on decisions that remain sound over time.”</div><p class="attribution">ALV HOMES <span>Our approach</span></p></section>`,
contact:()=>top('A PERSONAL CONVERSATION','Your next chapter<br><em>starts here.</em>','Tell us about the place, the purpose and the possibilities you have in mind.')+`<section class="contact-layout"><div class="contact-details"><p class="eyebrow">SPEAK WITH ALV HOMES</p><h2>Let’s begin<br><em>with you.</em></h2><a class="contact-number" href="tel:+905365157499">+90 536 515 74 99</a><p>Romiou Shaikh, Founder &amp; CEO<br>German · English · Turkish · Urdu</p><p>Russian and Ukrainian client support<br>with Viktoriia Darian.</p><a class="under-link" href="https://wa.me/905365157499" target="_blank" rel="noopener">Open WhatsApp</a><p>Kargicak Mahallesi, Sahil Caddesi No:67<br>Alanya / Antalya / Türkiye<br><br>Monday–Saturday, 09:00–18:00<br>Sunday closed</p></div><form id="inquiry-form" class="contact-form"><div class="form-grid"><div class="field"><label for="first-name">First name *</label><input id="first-name" name="firstName" autocomplete="given-name" required maxlength="80"></div><div class="field"><label for="last-name">Last name</label><input id="last-name" name="lastName" autocomplete="family-name" maxlength="80"></div><div class="field"><label for="email">Email *</label><input id="email" type="email" name="email" autocomplete="email" required maxlength="160"></div><div class="field"><label for="phone">Telephone</label><input id="phone" type="tel" name="phone" autocomplete="tel" maxlength="40"></div><div class="field full"><label for="language">Preferred language</label><select id="language" name="language">${['English','German','Turkish','Russian','Ukrainian','Urdu'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field full"><label for="message">What are you looking for? *</label><textarea id="message" name="message" rows="5" required maxlength="3000" placeholder="Location, property type, budget, and anything else that matters to you."></textarea></div></div><p class="form-help">This opens a draft in your email app. Review it and press Send there. Your inquiry is not sent by this website.</p><button class="button" type="submit">Prepare email inquiry</button><a class="under-link fallback-link" href="${official}inquiryform" target="_blank" rel="noopener">Use ALV’s inquiry form</a><p class="form-status" id="form-status" role="status"></p></form></section>`
};
let mm=null, scene=null, sceneToken=0, galleryTrigger=null, activeGallery=0, motionOff=false;
try{motionOff=sessionStorage.getItem('alv-motion')==='off'}catch{}
const systemMotion=matchMedia('(prefers-reduced-motion: reduce)');
const reduced=()=>systemMotion.matches||motionOff;
const imageFallbacks=()=>$$('img').forEach(img=>{if(img.complete&&!img.naturalWidth)img.parentElement.classList.add('image-failed');img.addEventListener('error',()=>img.parentElement.classList.add('image-failed'),{once:true});});
function cleanupMotion(){sceneToken++;mm?.revert();mm=null;galleryTrigger=null;scene?.dispose();scene=null;$('#threshold').classList.remove('ready');$('#gallery-prev').disabled=false;$('#gallery-next').disabled=false;}
function setGallery(n){activeGallery=Math.min(3,Math.max(0,n));$('#gallery-number').textContent=String(activeGallery+1).padStart(2,'0');$('#gallery-prev').disabled=activeGallery===0;$('#gallery-next').disabled=activeGallery===3;}
function setupMotion(){
 document.documentElement.classList.toggle('no-motion',reduced());$('#motion-toggle').setAttribute('aria-pressed',String(reduced()));$('#motion-toggle').textContent=reduced()?'Motion reduced':'Reduce motion';
 if(currentRoute!=='home'||reduced())return;
 mm=gsap.matchMedia();
 mm.add({desktop:'(min-width: 1025px) and (min-height: 820px) and (pointer: fine)',mobile:'(max-width: 1024px)',reduce:'(prefers-reduced-motion: reduce)'},context=>{
  if(context.conditions.reduce)return;
  gsap.fromTo('.statement-quote span',{opacity:.62,y:10},{opacity:1,y:0,stagger:.12,duration:.95,ease:'power2.out',scrollTrigger:{trigger:'.statement',start:'top 76%',once:true}});
  gsap.utils.toArray('.market-image img').forEach(img=>gsap.fromTo(img,{scale:1.07},{scale:1,ease:'none',scrollTrigger:{trigger:img.parentElement,start:'top bottom',end:'bottom top',scrub:.4}}));
  if(context.conditions.desktop){
   const heroState={p:0};
   gsap.to(heroState,{p:1,ease:'none',scrollTrigger:{trigger:'#hero',start:'top top',end:'+=420',pin:true,scrub:.35,onUpdate:()=>scene?.update(heroState.p)},onUpdate:()=>scene?.update(heroState.p)});
   gsap.to('.hero-photo',{scale:1.035,ease:'none',scrollTrigger:{trigger:'#hero',start:'top top',end:'+=420',scrub:.35}});
   const rail=$('#property-rail'),vp=$('.rail-viewport');
   const travel=()=>Math.max(0,rail.scrollWidth-vp.clientWidth+parseFloat(getComputedStyle(vp).paddingLeft)*2);
   if(travel()>0){
    vp.style.overflow='hidden';
    const anim=gsap.to(rail,{x:()=>-travel(),ease:'none',scrollTrigger:{trigger:'.gallery-stage',start:'top 82px',end:()=>`+=${travel()}`,pin:true,scrub:.28,invalidateOnRefresh:true,onUpdate:self=>{setGallery(Math.round(self.progress*3));gsap.set('.gallery-progress span',{scaleX:.25+self.progress*.75});}}});
    galleryTrigger=anim.scrollTrigger;
   }
   const token=++sceneToken;
   const ready=()=>{if(token!==sceneToken)return;import('./threshold.js').then(({createThreshold})=>{if(token!==sceneToken||reduced())return;try{scene=createThreshold($('#threshold'));scene.update(heroState.p)}catch{document.documentElement.dataset.webgl='fallback'}}).catch(()=>{document.documentElement.dataset.webgl='fallback'});};
   const heroImg=$('.hero-photo');if(heroImg.complete)ready();else heroImg.addEventListener('load',ready,{once:true});
   return ()=>{vp.style.overflow='';vp.scrollLeft=0;sceneToken++;scene?.dispose();scene=null;$('#threshold').classList.remove('ready');galleryTrigger=null;};
  }
 });
 document.fonts.ready.then(()=>ScrollTrigger.refresh());
 $$('img').forEach(img=>{if(!img.complete)img.addEventListener('load',()=>ScrollTrigger.refresh(),{once:true})});
}
function browseGallery(direction){const n=Math.max(0,Math.min(3,activeGallery+direction));if(galleryTrigger){scrollTo({top:galleryTrigger.start+(galleryTrigger.end-galleryTrigger.start)*n/3,behavior:reduced()?'instant':'smooth'})}else{const vp=$('.rail-viewport'),cards=$$('#property-rail .property-card');vp.scrollTo({left:cards[n].offsetLeft-cards[0].offsetLeft,behavior:reduced()?'instant':'smooth'});setGallery(n)}}
$('#gallery-prev').onclick=()=>browseGallery(-1);$('#gallery-next').onclick=()=>browseGallery(1);
$('.rail-viewport').addEventListener('scroll',()=>{if(galleryTrigger)return;const vp=$('.rail-viewport');setGallery(Math.round(vp.scrollLeft/Math.max(1,vp.scrollWidth-vp.clientWidth)*3));gsap.set('.gallery-progress span',{scaleX:.25+.75*vp.scrollLeft/Math.max(1,vp.scrollWidth-vp.clientWidth)});},{passive:true});
$('#property-rail').addEventListener('focusin',e=>{const card=e.target.closest('.property-card');if(!card)return;const n=+card.dataset.index;if(galleryTrigger){const top=galleryTrigger.start+(galleryTrigger.end-galleryTrigger.start)*n/3;scrollTo({top,behavior:'instant'});}else{$('.rail-viewport').scrollTo({left:card.offsetLeft-$('#property-rail .property-card').offsetLeft,behavior:'instant'})}setGallery(n)});
let currentRoute='home';
function parseRoute(){let v;try{v=decodeURIComponent(location.hash.slice(1))}catch{v='home'};const [route,filter]=v.split(':');return {route:templates[route]?route:'home',filter,anchor:route==='statement'?'statement':null};}
function updateHeader(){$('#header').classList.toggle('scrolled',scrollY>35||currentRoute!=='home')}
function closeMenu(){const nav=$('#navigation');nav.classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}
$('#menu').onclick=()=>{const open=$('#navigation').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));if(open)$('#navigation a').focus();};
addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#navigation').classList.contains('open')){closeMenu();$('#menu').focus();}});
function filterProperties(filter='All'){
 const aliases={'Sea View':'Sea view','Sea Front':'Sea front','Payment Plan':'Payment plan'};filter=aliases[filter]||filter;
 const allowed=['All','Villas','Apartments','Sea front','Sea view','Bali','Luxury','Payment plan'];if(!allowed.includes(filter))filter='All';
 const list=properties.filter(p=>filter==='All'||p.filters.includes(filter));$('#catalog-grid').innerHTML=list.map(card).join('');$('#catalog-count').textContent=`${list.length} ${list.length===1?'property':'properties'} in this selection · ${filter}`;$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));imageFallbacks();
}
function mountContact(){const form=$('#inquiry-form');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),subject=`Property inquiry from ${f.get('firstName')} ${f.get('lastName')||''}`.trim(),body=`Name: ${f.get('firstName')} ${f.get('lastName')||''}\nEmail: ${f.get('email')}\nTelephone: ${f.get('phone')||'Not provided'}\nPreferred language: ${f.get('language')}\n\n${f.get('message')}`;const href=`mailto:alanya.luxury.villas.and.homes@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;$('#form-status').textContent='Your email draft is ready. Complete sending in your email app. If it did not open, use ALV’s inquiry form above.';const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener';a.textContent='Open email draft';$('#form-status').append(' ',a);a.click();});}
function renderRoute({focus=true,restore=0}={}){const {route,filter,anchor}=parseRoute();cleanupMotion();currentRoute=route;closeMenu();$('#home-page').hidden=route!=='home';$('#route-page').hidden=route==='home';$('#route-page').innerHTML=route==='home'?'':templates[route]();document.title=route==='home'?'ALV Homes | Privacy. Precision. Performance.':`${route[0].toUpperCase()+route.slice(1)} | ALV Homes`;$$('#navigation a').forEach(a=>{if(a.hash===`#${route}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(route==='properties'){filterProperties(filter);$$('[data-filter]').forEach(button=>button.onclick=()=>{saveScroll();history.pushState({scroll:0},'',`#properties:${encodeURIComponent(button.dataset.filter)}`);filterProperties(button.dataset.filter);});}mountContact();imageFallbacks();setupMotion();updateHeader();requestAnimationFrame(()=>{ScrollTrigger.refresh();if(anchor){$('#statement').scrollIntoView({behavior:'instant'});}else scrollTo({top:restore,behavior:'instant'});if(focus){const h=route==='home'?$('.hero h1'):$('#route-page h1');h?.focus({preventScroll:true});}});}
function saveScroll(){history.replaceState({...history.state,scroll:scrollY},'')}
history.scrollRestoration='manual';
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;if(a.hash==='#main'){e.preventDefault();$('#main').focus();return;}e.preventDefault();saveScroll();history.pushState({scroll:0},'',a.hash);if(a.hash==='#statement'&&currentRoute==='home'){$('#statement').scrollIntoView({behavior:reduced()?'instant':'smooth'});return;}renderRoute();});
addEventListener('popstate',e=>renderRoute({restore:e.state?.scroll||0}));
addEventListener('hashchange',()=>{const p=parseRoute();if(p.route!==currentRoute)renderRoute();});
let scrollFrame=0;addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(()=>{updateHeader();scrollFrame=0;});},{passive:true});
$('#motion-toggle').onclick=()=>{motionOff=!motionOff;try{sessionStorage.setItem('alv-motion',motionOff?'off':'on')}catch{};const y=scrollY;cleanupMotion();setupMotion();requestAnimationFrame(()=>scrollTo({top:Math.min(y,document.documentElement.scrollHeight-innerHeight),behavior:'instant'}));};
systemMotion.addEventListener('change',()=>{cleanupMotion();setupMotion();});
addEventListener('pagehide',saveScroll);
renderRoute({focus:false,restore:history.state?.scroll||0});
